family: "25h9"            # tag family, one of 16h5, 25h7, 25h9, 36h10, 36h11, 36artoolkit
size: 0.356             # tag edge size in meter, 0.157
max_hamming: 0          # maximum allowed hamming distance (corrected bits)
z_up: true              # rotate about x-axis to have Z pointing upwards

# see "apriltag.h" for more documentation on these optional parameters
decimate: 1.0           # decimate resolution for quad detection
blur: 0.0               # sigma of Gaussian blur for quad detection
refine-edges: 1         # snap to strong gradients
threads: 2              # number of threads
refine-decode: 1        # increase the number of detected tags
refine-pose: 0          # increase the accuracy of the extracted pose
debug: 1                # write additional debugging images to current working directory

# optional list of tags
#tag_ids: [0, 1, 2]            # tag ID
#tag_frames: [object0, object1, object2]  # optional frame name
#tag_sizes: [0.203, 0.203, 0.203]   # optional tag-specific edge size
